// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminLeaveBalance(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminLeaveBalance'](arg1, arg2, arg3);
}

export function ApplyLeave(arg1, arg2) {
  return window['go']['main']['App']['ApplyLeave'](arg1, arg2);
}

export function ApproveLeave(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApproveLeave'](arg1, arg2, arg3);
}

export function ApprovePayrollBatch(arg1, arg2) {
  return window['go']['main']['App']['ApprovePayrollBatch'](arg1, arg2);
}

export function CancelLeave(arg1, arg2, arg3) {
  return window['go']['main']['App']['CancelLeave'](arg1, arg2, arg3);
}

export function ConvertAbsenceToLeave(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertAbsenceToLeave'](arg1, arg2, arg3, arg4);
}

export function CreateEmployee(arg1, arg2) {
  return window['go']['main']['App']['CreateEmployee'](arg1, arg2);
}

export function CreateLeaveType(arg1, arg2) {
  return window['go']['main']['App']['CreateLeaveType'](arg1, arg2);
}

export function CreatePayrollBatch(arg1, arg2) {
  return window['go']['main']['App']['CreatePayrollBatch'](arg1, arg2);
}

export function DeactivateLeaveType(arg1, arg2) {
  return window['go']['main']['App']['DeactivateLeaveType'](arg1, arg2);
}

export function DeleteEmployee(arg1, arg2) {
  return window['go']['main']['App']['DeleteEmployee'](arg1, arg2);
}

export function ExportPayrollBatchCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportPayrollBatchCSV'](arg1, arg2);
}

export function GeneratePayrollEntries(arg1, arg2) {
  return window['go']['main']['App']['GeneratePayrollEntries'](arg1, arg2);
}

export function GetEmployee(arg1, arg2) {
  return window['go']['main']['App']['GetEmployee'](arg1, arg2);
}

export function GetPayrollBatch(arg1, arg2) {
  return window['go']['main']['App']['GetPayrollBatch'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListEmployeeDepartments(arg1) {
  return window['go']['main']['App']['ListEmployeeDepartments'](arg1);
}

export function ListEmployees(arg1, arg2) {
  return window['go']['main']['App']['ListEmployees'](arg1, arg2);
}

export function ListLeaveRequests(arg1, arg2) {
  return window['go']['main']['App']['ListLeaveRequests'](arg1, arg2);
}

export function ListLeaveTypes(arg1) {
  return window['go']['main']['App']['ListLeaveTypes'](arg1);
}

export function ListLockedLeaveDates(arg1, arg2) {
  return window['go']['main']['App']['ListLockedLeaveDates'](arg1, arg2);
}

export function ListPayrollBatches(arg1, arg2) {
  return window['go']['main']['App']['ListPayrollBatches'](arg1, arg2);
}

export function LockLeaveDate(arg1, arg2) {
  return window['go']['main']['App']['LockLeaveDate'](arg1, arg2);
}

export function LockPayrollBatch(arg1, arg2) {
  return window['go']['main']['App']['LockPayrollBatch'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function MasterDeleteLeave(arg1, arg2) {
  return window['go']['main']['App']['MasterDeleteLeave'](arg1, arg2);
}

export function MasterUpdateLeave(arg1, arg2, arg3) {
  return window['go']['main']['App']['MasterUpdateLeave'](arg1, arg2, arg3);
}

export function Me(arg1) {
  return window['go']['main']['App']['Me'](arg1);
}

export function MeLeaveBalance(arg1, arg2) {
  return window['go']['main']['App']['MeLeaveBalance'](arg1, arg2);
}

export function Refresh(arg1) {
  return window['go']['main']['App']['Refresh'](arg1);
}

export function RejectLeave(arg1, arg2, arg3) {
  return window['go']['main']['App']['RejectLeave'](arg1, arg2, arg3);
}

export function UnlockLeaveDate(arg1, arg2) {
  return window['go']['main']['App']['UnlockLeaveDate'](arg1, arg2);
}

export function UpdateEmployee(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEmployee'](arg1, arg2, arg3);
}

export function UpdateLeaveType(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateLeaveType'](arg1, arg2, arg3);
}

export function UpdatePayrollEntryAmounts(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePayrollEntryAmounts'](arg1, arg2, arg3);
}
