// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<main.AuthResponse>;

export function Logout(arg1:string):Promise<void>;

export function Me(arg1:string):Promise<main.MeResponse>;

export function Refresh(arg1:string):Promise<main.AuthResponse>;
