// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {leave} from '../models';
import {employees} from '../models';

export function AdminLeaveBalance(arg1:string,arg2:number,arg3:number):Promise<main.LeaveBalanceResponse>;

export function ApplyLeave(arg1:string,arg2:leave.ApplyInput):Promise<main.LeaveRequestResponse>;

export function ApproveLeave(arg1:string,arg2:number,arg3:leave.DecisionInput):Promise<main.LeaveRequestResponse>;

export function CancelLeave(arg1:string,arg2:number,arg3:leave.DecisionInput):Promise<main.LeaveRequestResponse>;

export function ConvertAbsenceToLeave(arg1:string,arg2:number,arg3:string,arg4:number):Promise<main.LeaveRequestResponse>;

export function CreateEmployee(arg1:string,arg2:employees.UpsertEmployeeInput):Promise<main.EmployeeResponse>;

export function CreateLeaveType(arg1:string,arg2:leave.LeaveTypeInput):Promise<main.LeaveTypeResponse>;

export function DeactivateLeaveType(arg1:string,arg2:number):Promise<void>;

export function DeleteEmployee(arg1:string,arg2:number):Promise<void>;

export function GetEmployee(arg1:string,arg2:number):Promise<main.EmployeeResponse>;

export function Greet(arg1:string):Promise<string>;

export function ListEmployeeDepartments(arg1:string):Promise<main.DepartmentListResponse>;

export function ListEmployees(arg1:string,arg2:employees.EmployeeListFilter):Promise<main.EmployeeListResponse>;

export function ListLeaveRequests(arg1:string,arg2:leave.RequestFilter):Promise<main.LeaveRequestListResponse>;

export function ListLeaveTypes(arg1:string):Promise<main.LeaveTypeListResponse>;

export function ListLockedLeaveDates(arg1:string,arg2:number):Promise<main.LockedDateListResponse>;

export function LockLeaveDate(arg1:string,arg2:leave.LockDateInput):Promise<main.LockedDateResponse>;

export function Login(arg1:string,arg2:string):Promise<main.AuthResponse>;

export function Logout(arg1:string):Promise<void>;

export function MasterDeleteLeave(arg1:string,arg2:number):Promise<void>;

export function MasterUpdateLeave(arg1:string,arg2:number,arg3:leave.ApplyInput):Promise<main.LeaveRequestResponse>;

export function Me(arg1:string):Promise<main.MeResponse>;

export function MeLeaveBalance(arg1:string,arg2:number):Promise<main.LeaveBalanceResponse>;

export function Refresh(arg1:string):Promise<main.AuthResponse>;

export function RejectLeave(arg1:string,arg2:number,arg3:leave.DecisionInput):Promise<main.LeaveRequestResponse>;

export function UnlockLeaveDate(arg1:string,arg2:string):Promise<void>;

export function UpdateEmployee(arg1:string,arg2:number,arg3:employees.UpsertEmployeeInput):Promise<main.EmployeeResponse>;

export function UpdateLeaveType(arg1:string,arg2:number,arg3:leave.LeaveTypeInput):Promise<main.LeaveTypeResponse>;
